### ISSUE TITLE
Emails 

### ISSUE THREAD

**Issue by demontech** [helgatheviking/wc-shipping-contact#1]

**Comment by helgatheviking** [comment]
![image](https://github.com/helgatheviking/wc-shipping-contact/assets/507025/97410cd2-9a40-4c7a-9f1f-c114baf42cee)

**Comment by helgatheviking** [comment]
well i think I fixed it. try v 1.1.1 from the latest trunk. if that doesn't resolve it, I am open to PRs as this plugin doesn't get a lot of support.
